/* Generated by Yosys 0.9 (git sha1 1979e0b) */

/* top =  1  */
/* src = "top.v:1" */
module smart_gate_controller(clk_i, reset_ni, car_i, pay_ok_i, clear_i, cnt_reset_i, gate_open_o, gate_close_o, red_o, yellow_o, green_o, car_count_o);
  /* src = "top.v:28" */
  wire [7:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  /* src = "top.v:13" */
  output [7:0] car_count_o;
  reg [7:0] car_count_o;
  /* src = "top.v:4" */
  input car_i;
  /* src = "top.v:6" */
  input clear_i;
  /* src = "top.v:2" */
  input clk_i;
  /* src = "top.v:7" */
  input cnt_reset_i;
  /* src = "top.v:9" */
  output gate_close_o;
  /* src = "top.v:8" */
  output gate_open_o;
  /* src = "top.v:12" */
  output green_o;
  /* src = "top.v:24" */
  wire [2:0] next_state;
  /* src = "top.v:25" */
  wire [3:0] next_timer;
  /* src = "top.v:5" */
  input pay_ok_i;
  /* src = "top.v:10" */
  output red_o;
  /* src = "top.v:3" */
  input reset_ni;
  /* src = "top.v:24" */
  reg [2:0] state;
  /* src = "top.v:25" */
  reg [3:0] timer;
  /* src = "top.v:11" */
  output yellow_o;
  assign _01_ = ~clear_i;
  assign _02_ = state[1] & ~(state[2]);
  assign green_o = state[0] & _02_;
  assign _03_ = ~(state[1] | state[0]);
  assign gate_close_o = state[2] & _03_;
  assign _04_ = state[0] | ~(_02_);
  assign _05_ = ~(state[2] | state[1]);
  assign _06_ = state[0] & _05_;
  assign _07_ = ~(gate_close_o | _06_);
  assign yellow_o = ~(_04_ & _07_);
  assign _08_ = ~(timer[1] | timer[2]);
  assign _09_ = _08_ & ~(timer[3]);
  assign _10_ = _09_ & ~(timer[0]);
  assign _11_ = ~(_06_ & _10_);
  assign _12_ = _01_ | _04_;
  assign _13_ = ~(green_o & _09_);
  assign _14_ = car_i & pay_ok_i;
  assign _15_ = _03_ & ~(state[2]);
  assign _16_ = ~(_14_ & _15_);
  assign _17_ = _13_ & _16_;
  assign _18_ = _12_ & _17_;
  assign next_state[0] = ~(_11_ & _18_);
  assign _19_ = _10_ | ~(_06_);
  assign _20_ = _04_ & _13_;
  assign next_state[1] = ~(_19_ & _20_);
  assign next_state[2] = green_o & ~(_09_);
  assign red_o = _07_ & ~(_02_);
  assign _00_[0] = car_count_o[0] & ~(cnt_reset_i);
  assign _00_[1] = car_count_o[1] & ~(cnt_reset_i);
  assign _00_[2] = car_count_o[2] & ~(cnt_reset_i);
  assign _00_[3] = car_count_o[3] & ~(cnt_reset_i);
  assign _00_[4] = car_count_o[4] & ~(cnt_reset_i);
  assign _00_[5] = car_count_o[5] & ~(cnt_reset_i);
  assign _00_[6] = car_count_o[6] & ~(cnt_reset_i);
  assign _00_[7] = car_count_o[7] & ~(cnt_reset_i);
  assign _21_ = _14_ | ~(_15_);
  assign _22_ = clear_i | _04_;
  assign _23_ = ~(_21_ & _22_);
  assign _24_ = _13_ & ~(_23_);
  assign _25_ = timer[0] | _24_;
  assign next_timer[0] = ~(_11_ & _25_);
  assign _26_ = timer[0] & ~(_13_);
  assign _27_ = timer[0] & timer[1];
  assign _28_ = timer[0] ^ timer[1];
  assign _29_ = _23_ & _28_;
  assign next_timer[1] = _26_ | _29_;
  assign _30_ = ~(timer[2] & _27_);
  assign _31_ = timer[2] ^ _27_;
  assign next_timer[2] = _23_ & _31_;
  assign _32_ = ~(timer[3] ^ _30_);
  assign next_timer[3] = _23_ & _32_;
  assign gate_open_o = green_o | ~(_12_);
  /* src = "top.v:28" */
  always @(posedge clk_i or negedge reset_ni)
    if (!reset_ni)
      car_count_o[0] <= 0;
    else
      car_count_o[0] <= _00_[0];
  /* src = "top.v:28" */
  always @(posedge clk_i or negedge reset_ni)
    if (!reset_ni)
      car_count_o[1] <= 0;
    else
      car_count_o[1] <= _00_[1];
  /* src = "top.v:28" */
  always @(posedge clk_i or negedge reset_ni)
    if (!reset_ni)
      car_count_o[2] <= 0;
    else
      car_count_o[2] <= _00_[2];
  /* src = "top.v:28" */
  always @(posedge clk_i or negedge reset_ni)
    if (!reset_ni)
      car_count_o[3] <= 0;
    else
      car_count_o[3] <= _00_[3];
  /* src = "top.v:28" */
  always @(posedge clk_i or negedge reset_ni)
    if (!reset_ni)
      car_count_o[4] <= 0;
    else
      car_count_o[4] <= _00_[4];
  /* src = "top.v:28" */
  always @(posedge clk_i or negedge reset_ni)
    if (!reset_ni)
      car_count_o[5] <= 0;
    else
      car_count_o[5] <= _00_[5];
  /* src = "top.v:28" */
  always @(posedge clk_i or negedge reset_ni)
    if (!reset_ni)
      car_count_o[6] <= 0;
    else
      car_count_o[6] <= _00_[6];
  /* src = "top.v:28" */
  always @(posedge clk_i or negedge reset_ni)
    if (!reset_ni)
      car_count_o[7] <= 0;
    else
      car_count_o[7] <= _00_[7];
  /* src = "top.v:28" */
  always @(posedge clk_i or negedge reset_ni)
    if (!reset_ni)
      state[0] <= 0;
    else
      state[0] <= next_state[0];
  /* src = "top.v:28" */
  always @(posedge clk_i or negedge reset_ni)
    if (!reset_ni)
      state[1] <= 0;
    else
      state[1] <= next_state[1];
  /* src = "top.v:28" */
  always @(posedge clk_i or negedge reset_ni)
    if (!reset_ni)
      state[2] <= 0;
    else
      state[2] <= next_state[2];
  /* src = "top.v:28" */
  always @(posedge clk_i or negedge reset_ni)
    if (!reset_ni)
      timer[0] <= 0;
    else
      timer[0] <= next_timer[0];
  /* src = "top.v:28" */
  always @(posedge clk_i or negedge reset_ni)
    if (!reset_ni)
      timer[1] <= 0;
    else
      timer[1] <= next_timer[1];
  /* src = "top.v:28" */
  always @(posedge clk_i or negedge reset_ni)
    if (!reset_ni)
      timer[2] <= 0;
    else
      timer[2] <= next_timer[2];
  /* src = "top.v:28" */
  always @(posedge clk_i or negedge reset_ni)
    if (!reset_ni)
      timer[3] <= 0;
    else
      timer[3] <= next_timer[3];
endmodule
